print failed tests

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -6,7 +6,7 @@ on:
 
 jobs:
 
-  test:
+  run-tests:
 
     runs-on: ubuntu-latest
 
@@ -22,4 +22,4 @@ jobs:
       run: docker build . --file DockerTestFile --tag framework-test-image
         
     - name: Run the test image
-      run: docker run --rm framework-test-image
+      run: docker run --rm framework-test-image || echo "::error $( sed -ne '/The following tests FAILED/,$ p' testLog.log)"
